// Mocks generated by Mockito 5.0.7 from annotations
// in property_inspect/test/login_controller_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:property_inspect/domain/repository/analytics_repo.dart' as _i3;
import 'package:property_inspect/domain/repository/logout_repo.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [LogoutRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutRepo extends _i1.Mock implements _i2.LogoutRepo {
  MockLogoutRepo() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [AnalyticsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsRepo extends _i1.Mock implements _i3.AnalyticsRepo {
  MockAnalyticsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic sendEvent(String? type, Map<String, dynamic>? content) =>
      super.noSuchMethod(Invocation.method(#sendEvent, [type, content]));
}
