// Mocks generated by Mockito 5.0.7 from annotations
// in property_inspect/test/visitor_registration_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:property_inspect/domain/entities/visitor.dart' as _i3;
import 'package:property_inspect/domain/repository/visitor_registration.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [VisitorRegistration].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitorRegistration extends _i1.Mock
    implements _i2.VisitorRegistration {
  MockVisitorRegistration() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void createVisitorRegistration(_i3.Visitor? visitor) => super.noSuchMethod(
      Invocation.method(#createVisitorRegistration, [visitor]),
      returnValueForMissingStub: null);
}
