name: Run unit tests on push to develop
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: 'Get flutter packages'
        run: flutter pub get
      - name: 'Do unit tests'
        run: flutter test